from __future__ import annotations


NODE_HTML = """<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>CAMPEX Node</title>
  <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
  <style>
    :root{--black:#090a0c;--bg:#0b0d10;--side:#080b10;--panel:#171b21;--panel2:#20262e;--border:#313946;--border2:#252b34;--text:#f2f5f8;--muted:#9aa6b4;--subtle:#6f7b8a;--accent:#7db3ff;--blue:#2688ff;--green:#31c46b;--warn:#e2b245;--red:#ef5b5b;--shadow:0 .75rem 1.75rem rgba(0,0,0,.2);--font:"Inter","Segoe UI",ui-sans-serif,system-ui,sans-serif}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;color:var(--text);font:14px/1.45 var(--font);background:radial-gradient(circle at 18% -12%,#18324b 0,#0b0d10 48%,#06080b 100%)}button,input{font:inherit}button{cursor:pointer}a{text-decoration:none;color:inherit}
    .window{min-height:100vh;padding:24px}.app{min-height:calc(100vh - 48px);display:grid;grid-template-columns:264px 1fr;background:rgba(9,10,12,.94);border:1px solid rgba(49,57,70,.88);border-radius:8px;box-shadow:0 1.8rem 5rem rgba(0,0,0,.48);overflow:hidden}
    .side{display:flex;flex-direction:column;background:linear-gradient(180deg,#090a0c,#0c1117);border-right:1px solid var(--border2);padding:24px 18px}.brand{display:flex;align-items:center;gap:13px;margin-bottom:32px}.brand-mark{width:44px;height:44px;border-radius:8px;background:#102041;display:grid;place-items:center;overflow:hidden}.brand-mark img{width:100%;height:100%;object-fit:cover}.brand-title{font-weight:850;font-size:20px}.brand-title span{color:var(--accent)}.brand small,.side-bottom small{display:block;color:var(--muted);font-size:12px}
    .nav{display:grid;gap:7px}.nav button{height:44px;display:flex;align-items:center;gap:12px;border:0;border-radius:7px;background:transparent;color:#dce4ee;padding:0 13px;text-align:left}.nav button i{font-size:22px;color:#aeb9c6}.nav button.active{background:linear-gradient(90deg,#123679,#17243b);box-shadow:inset 3px 0 0 var(--blue)}.nav button.active i{color:#59a8ff}.side-bottom{margin-top:auto}.service{display:flex;align-items:center;gap:10px;color:#66e88e;font-weight:800;margin-bottom:6px}.dot{width:10px;height:10px;border-radius:99px;background:var(--red);box-shadow:0 0 0 5px rgba(239,91,91,.13)}.online .dot,.service .dot,.ONLINE .dot{background:var(--green);box-shadow:0 0 0 5px rgba(49,196,107,.14)}.DEGRADED .dot,.CONNECTING .dot{background:var(--warn);box-shadow:0 0 0 5px rgba(226,178,69,.14)}
    main{min-width:0;padding:22px}.top{display:flex;align-items:center;justify-content:space-between;gap:18px;padding-bottom:18px;margin-bottom:16px;border-bottom:1px solid var(--border2)}.headline{display:flex;align-items:center;gap:15px}.pulse{width:34px;height:34px;border-radius:99px;background:var(--green);box-shadow:0 0 0 9px rgba(49,196,107,.18)}h1{font-size:24px;line-height:1.1;margin:0 0 5px}.muted{color:var(--muted)}.cloud{display:flex;align-items:center;gap:16px}.cloud-state{color:#61e98d;font-weight:850}.button{height:40px;border:1px solid var(--border);border-radius:7px;background:linear-gradient(180deg,#202a35,#141b23);color:var(--text);font-weight:760;padding:0 14px;display:inline-flex;align-items:center;gap:8px}.button i{font-size:20px}.primary{background:linear-gradient(180deg,#0e75df,#0a54a9);border-color:#1266c3}.ghost{background:#111820}
    .page{display:none}.page.active{display:block}.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:14px}.card,.panel{background:linear-gradient(180deg,rgba(23,27,33,.98),rgba(14,18,24,.98));border:1px solid var(--border2);border-radius:8px;box-shadow:var(--shadow)}.card{display:grid;grid-template-columns:52px 1fr;gap:14px;padding:16px}.icon{width:48px;height:48px;border-radius:8px;background:#20262e;display:grid;place-items:center;color:#b9c7d8}.icon i{font-size:27px}.icon.blue{background:#17305c;color:#54a9ff}.card label{display:block;color:var(--muted);margin-bottom:4px}.card strong{font-size:22px}.bar{height:7px;border-radius:99px;background:#222d38;overflow:hidden;margin-top:10px}.bar span{height:100%;display:block;border-radius:inherit;background:linear-gradient(90deg,#31c46b,#79f0aa)}.panel{padding:16px}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:13px}.panel h2{font-size:16px;margin:0}.panel p{margin:2px 0 0;color:var(--muted)}.split{display:grid;grid-template-columns:1.35fr .95fr;gap:14px}.stack{display:grid;gap:14px}
    .camera-grid{display:grid;grid-template-columns:repeat(4,minmax(154px,1fr));gap:10px}.camera-card{position:relative;min-height:116px;overflow:hidden;border:1px solid #2c3845;border-radius:8px;background:linear-gradient(135deg,#182431,#0e151d);padding:10px}.camera-card:before{content:"";position:absolute;inset:36px 12px 12px;background:repeating-linear-gradient(90deg,rgba(125,179,255,.13) 0 1px,transparent 1px 24px),repeating-linear-gradient(0deg,rgba(125,179,255,.1) 0 1px,transparent 1px 22px)}.camera-card:after{content:"";position:absolute;right:-22px;bottom:-18px;width:96px;height:66px;border:1px solid rgba(125,179,255,.18);border-radius:8px;transform:rotate(-10deg)}.cam-title{position:relative;display:flex;align-items:flex-start;justify-content:space-between;gap:10px;font-weight:850}.cam-status{position:relative;display:inline-flex;align-items:center;gap:6px;color:#65e98f;font-weight:800;font-size:12px}.cam-meta{position:absolute;left:10px;right:10px;bottom:9px;display:flex;justify-content:space-between;gap:8px;padding:5px 7px;color:#d2dae4;background:rgba(7,10,14,.58);border:1px solid rgba(255,255,255,.06);border-radius:6px;font-size:12px}
    .row{display:grid;grid-template-columns:84px 1fr 130px 112px;gap:12px;align-items:center;border-top:1px solid var(--border2);padding:10px 6px}.row:first-child,.sync-row:first-child{border-top:0}.event-type{color:#8cbcff;font-weight:800}.event-type.warn{color:#ff6c6c}.sync-row{display:grid;grid-template-columns:34px 1fr auto;gap:10px;align-items:center;border-top:1px solid var(--border2);padding:11px 6px}.sync-row i{font-size:22px;color:#aeb9c6}.pill{display:inline-flex;align-items:center;gap:7px;border-radius:999px;background:rgba(49,196,107,.13);color:#71eba0;padding:5px 10px;font-size:12px;font-weight:850}.list{display:grid;gap:10px}.list-item{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px;border:1px solid var(--border2);border-radius:8px;background:#111820}.list-item strong{display:block}.list-item small{color:var(--muted)}
    form{display:grid;gap:10px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{color:var(--muted);font-size:12px}input,select{width:100%;height:38px;margin-top:6px;color:var(--text);background:#0d131a;border:1px solid var(--border2);border-radius:7px;padding:0 10px}.actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.status{min-height:20px;color:var(--muted)}code{color:#8fc3ff;word-break:break-all}.about-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.logo-wide{max-width:190px;margin-bottom:14px}
    @media(max-width:1180px){.kpis{grid-template-columns:repeat(2,1fr)}.camera-grid{grid-template-columns:repeat(2,1fr)}.split,.about-grid{grid-template-columns:1fr}}@media(max-width:760px){.window{padding:0}.app{grid-template-columns:1fr;border-radius:0}.side{display:none}.top,.cloud{align-items:flex-start;flex-direction:column}.kpis,.camera-grid,.form-grid{grid-template-columns:1fr}.row{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <div class="window"><div class="app">
    <aside class="side">
      <div class="brand"><div class="brand-mark"><img src="/assets/simbolo.jpeg" alt="CAMPEX"></div><div><div class="brand-title">CAMPEX <span>Node</span></div><small>Processamento local de cameras e IA</small></div></div>
      <nav class="nav">
        <button class="active" data-page="overview"><i class="bx bxs-dashboard"></i>Visao geral</button>
        <button data-page="cameras"><i class="bx bxs-camera-home"></i>Cameras</button>
        <button data-page="processing"><i class="bx bx-pulse"></i>Processamento</button>
        <button data-page="events"><i class="bx bxs-bell-ring"></i>Eventos</button>
        <button data-page="sync"><i class="bx bx-cloud-upload"></i>Sincronizacao</button>
        <button data-page="diagnostics"><i class="bx bx-terminal"></i>Diagnostico</button>
        <button data-page="settings"><i class="bx bxs-cog"></i>Configuracoes</button>
        <button data-page="about"><i class="bx bx-info-circle"></i>Sobre</button>
      </nav>
      <div class="side-bottom"><div class="service"><span class="dot"></span>Servico em execucao</div><small>Iniciado com o Windows</small><br><br><small>Versao 0.1.0<br>CAMPEX Node</small></div>
    </aside>
    <main>
      <header class="top"><div class="headline"><div class="pulse"></div><div><h1 id="page-title">Node Ativo</h1><div class="muted" id="page-subtitle">Processando cameras e enviando eventos para a nuvem</div></div></div><div class="cloud"><div><div class="cloud-state" id="cloud-badge">Verificando Cloud</div><div class="muted" id="sync-caption">Ultima sincronizacao: aguardando</div></div><button class="button" id="sync-button" type="button"><i class="bx bx-refresh"></i>Forcar sincronizacao</button></div></header>
      <section class="page active" id="page-overview">
        <section class="kpis"><div class="card"><div class="icon"><i class="bx bxs-camera"></i></div><div><label>Cameras ativas</label><strong><span id="online">0</span> / <span id="total">0</span></strong><div class="bar"><span id="camera-bar"></span></div></div></div><div class="card"><div class="icon"><i class="bx bx-pulse"></i></div><div><label>Processamento IA</label><strong>Em execucao</strong><div class="muted">Deteccao, contagem e eventos</div></div></div><div class="card"><div class="icon blue"><i class="bx bx-cloud-upload"></i></div><div><label>Eventos na fila</label><strong id="queue">0</strong><div class="muted">Sincronizacao segura com a Cloud</div></div></div><div class="card"><div class="icon"><i class="bx bx-data"></i></div><div><label>Armazenamento local</label><strong>SQLite</strong><div class="bar"><span style="width:38%;background:linear-gradient(90deg,#6978ff,#37a4ff)"></span></div></div></div></section>
        <section class="panel"><div class="panel-head"><div><h2>Cameras recebidas da Cloud</h2><p>Status operacional sem exibir imagens das cameras</p></div><button class="button primary" id="diagnostics-button" type="button"><i class="bx bx-health"></i>Diagnostico</button></div><div class="camera-grid" id="cameras"></div></section>
        <section class="split" style="margin-top:14px"><div class="panel"><div class="panel-head"><h2>Eventos recentes <span class="muted">(processados localmente)</span></h2><button class="button ghost" data-page-jump="events">Ver todos</button></div><div id="events-list"></div></div><div class="panel"><div class="panel-head"><h2>Sincronizacao com a Cloud</h2><span class="pill online"><span class="dot"></span>Conectado</span></div><div id="sync-summary"></div></div></section>
      </section>
      <section class="page" id="page-cameras"><div class="split"><div class="panel"><div class="panel-head"><div><h2>Cameras</h2><p>Configuracoes chegam da Cloud; cameras locais podem ser adicionadas para teste.</p></div><button class="button" id="sync-button-cameras" type="button"><i class="bx bx-refresh"></i>Atualizar</button></div><div class="camera-grid" id="cameras-page"></div></div><div class="panel"><h2>Adicionar RTSP local</h2><form id="camera-form"><label>Nome da camera<input name="camera_name" placeholder="Portao principal" /></label><label>URL RTSP<input name="rtsp_url" placeholder="rtsp://usuario:senha@192.168.1.10/stream" /></label><label><input name="enabled" type="checkbox" checked style="width:auto;height:auto;margin-right:8px">Ativar worker apos salvar</label><div class="actions"><button class="button" type="button" id="test-camera-button"><i class="bx bx-wifi"></i>Testar conexao</button><button class="button primary" type="submit"><i class="bx bx-plus"></i>Salvar e ativar</button></div><p class="status" id="camera-form-status"></p></form></div></div></section>
      <section class="page" id="page-processing"><div class="split"><div class="panel"><div class="panel-head"><div><h2>Processamento</h2><p>Motor local de IA, captura e eventos.</p></div><span class="pill online"><span class="dot"></span>Ativo</span></div><div id="processing-page" class="list"></div></div><div class="panel"><h2>Modelos ativos</h2><div class="list"><div class="list-item"><div><strong>Deteccao</strong><small>YOLO local quando disponivel; fallback seguro.</small></div><span>OK</span></div><div class="list-item"><div><strong>Tracking</strong><small>Associacao temporal de objetos.</small></div><span>OK</span></div><div class="list-item"><div><strong>Eventos</strong><small>Regras locais antes da Cloud.</small></div><span>OK</span></div></div></div></div></section>
      <section class="page" id="page-events"><div class="panel"><div class="panel-head"><div><h2>Eventos</h2><p>Eventos processados localmente e enviados para a Cloud.</p></div><span class="pill"><i class="bx bx-shield-quarter"></i>Sem video bruto continuo</span></div><div id="events-page"></div></div></section>
      <section class="page" id="page-sync"><div class="split"><div class="panel"><div class="panel-head"><h2>Fila e conexao</h2><span class="pill online"><span class="dot"></span>Online</span></div><div id="sync-page"></div></div><div class="panel"><h2>Pareamento local</h2><p>Use somente na instalacao ou troca de empresa.</p><form id="connect-form"><div class="form-grid"><label>Backend Cloud<input name="cloud_url" placeholder="https://campexback.vercel.app/api/v1" /></label><label>Codigo legado<input name="pairing_code" autocomplete="off" placeholder="CXP-7KQ2-N91P" /></label></div><label>Nome deste Node<input name="node_name" placeholder="RBA-NODE-01" /></label><div class="actions"><button class="button primary" type="button" id="start-pairing-button"><i class="bx bx-barcode-reader"></i>Gerar codigo neste Node</button><button class="button" type="submit"><i class="bx bx-link"></i>Parear codigo legado</button><span class="status" id="form-status"></span></div><div id="local-pairing-code" class="panel" style="display:none;margin-top:12px"></div></form></div></div></section>
      <section class="page" id="page-diagnostics"><div class="split"><div class="panel"><div class="panel-head"><div><h2>Diagnostico</h2><p>Sistema, banco local, rede e cameras.</p></div><button class="button" id="diagnostics-button-page" type="button"><i class="bx bx-refresh"></i>Atualizar</button></div><div id="diagnostics-page" class="list"></div></div><div class="panel"><h2>Logs</h2><div class="list"><div class="list-item"><div><strong>Servico</strong><small>Executando como processo local.</small></div><span>OK</span></div><div class="list-item"><div><strong>Cloud</strong><small>Heartbeat e sincronizacao controlados pelo Node.</small></div><span id="diag-cloud">-</span></div></div></div></div></section>
      <section class="page" id="page-settings"><div class="split"><div class="panel"><h2>Configuracoes locais</h2><div class="list"><div class="list-item"><div><strong>Geral</strong><small>Identidade do Node e empresa pareada.</small></div><span>OK</span></div><div class="list-item"><div><strong>Inicializacao</strong><small>Node inicia mesmo sem navegador aberto.</small></div><span class="pill online">Ativo</span></div><div class="list-item"><div><strong>Armazenamento</strong><small>SQLite em pasta de dados do usuario.</small></div><span id="data-dir-label">OK</span></div><div class="list-item"><div><strong>Logs</strong><small>Rotativos e persistentes.</small></div><span id="logs-dir-label">OK</span></div><div class="list-item"><div><strong>Rede</strong><small>Saida HTTPS para CAMPEX Cloud, sem portas abertas.</small></div><span>OK</span></div><div class="list-item"><div><strong>Atualizacoes</strong><small>Preparado para pacote Windows.</small></div><span>Manual</span></div><div class="list-item"><div><strong>Avancado</strong><small>Operacoes sensiveis ficam isoladas.</small></div><span>Restrito</span></div></div></div><div class="panel"><h2>Identidade</h2><p>Node ID</p><code id="node-id">-</code><br><br><p>Cloud</p><code id="cloud-url-label">-</code><br><br><p>Uptime</p><code id="uptime-label">-</code><br><br><p>CPU/RAM</p><code id="resources-label">-</code></div></div></section>
      <section class="page" id="page-about"><div class="about-grid"><div class="panel"><img class="logo-wide" src="/assets/campex-logo-white.png" alt="CAMPEX"><h2>CAMPEX Node</h2><p>Agente operacional local para cameras, IA, eventos e sincronizacao com a CAMPEX Cloud.</p></div><div class="panel"><h2>Arquitetura</h2><div class="list"><div class="list-item"><strong>Cameras da empresa</strong><small>RTSP/ONVIF na rede local</small></div><div class="list-item"><strong>CAMPEX Node</strong><small>Processamento local e fila offline</small></div><div class="list-item"><strong>CAMPEX Cloud</strong><small>API, dashboard, relatorios e alertas</small></div></div></div></div></section>
    </main>
  </div></div>
  <script>
    const titles={overview:['Node Ativo','Processando cameras e enviando eventos para a nuvem'],cameras:['Cameras','Status de captura e processamento local'],processing:['Processamento','IA local, captura e eventos sem enviar video bruto'],events:['Eventos','Ocorrencias detectadas e sincronizadas'],sync:['Sincronizacao','Conexao segura entre Node e CAMPEX Cloud'],diagnostics:['Diagnostico','Sistema local, rede, banco e cameras'],settings:['Configuracoes','Operacao local do servico Windows'],about:['Sobre','Arquitetura hibrida CAMPEX']};
    const eventTypes=['Pessoa detectada','Veiculo detectado','Pessoa detectada','Movimento suspeito','Pessoa detectada','Area sem atividade'];
    const statusEl=()=>document.querySelector('#form-status');function nowText(){return new Date().toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'});}
    function setPage(page){document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.id===`page-${page}`));document.querySelectorAll('.nav button').forEach(btn=>btn.classList.toggle('active',btn.dataset.page===page));document.querySelector('#page-title').textContent=titles[page][0];document.querySelector('#page-subtitle').textContent=titles[page][1];}
    function cameraCard(cam,index){const status=cam.status||'OFFLINE';const people=status==='ONLINE'?((index%4)+1):0;const vehicles=status==='ONLINE'?(index%3):0;return `<div class="camera-card ${status}"><div class="cam-title"><span>${String(index+1).padStart(2,'0')} - ${cam.name}</span><span class="cam-status"><span class="dot"></span>${status}</span></div><div class="cam-meta"><span>Pessoas: ${people}</span><span>Veiculos: ${vehicles}</span></div></div>`;}
    function eventRows(cameras){const names=(cameras||[]).map(c=>c.name);return eventTypes.map((type,index)=>{const warn=type.includes('suspeito');const camera=names[index%Math.max(names.length,1)]||'Aguardando camera';const minute=String(42-index).padStart(2,'0');return `<div class="row"><span>09:${minute}:17</span><span class="event-type ${warn?'warn':''}">${type}</span><span>${camera}</span><span class="muted">Confianca: ${98-index*2}%</span></div>`;}).join('');}
    function formatTime(value){return value?new Date(value).toLocaleString('pt-BR'):'aguardando';}
    function uptimeText(seconds){seconds=Number(seconds||0);const h=Math.floor(seconds/3600);const m=Math.floor((seconds%3600)/60);const s=seconds%60;return `${h}h ${m}m ${s}s`;}
    function syncRows(data){return `<div class="sync-row"><i class="bx bx-calendar-check"></i><span>Ultima sincronizacao</span><strong>${formatTime(data.last_sync_at)}</strong></div><div class="sync-row"><i class="bx bx-cloud-upload"></i><span>Eventos pendentes</span><strong>${data.queue_size||0}</strong></div><div class="sync-row"><i class="bx bx-cog"></i><span>Ultimo heartbeat</span><strong>${formatTime(data.last_heartbeat_at)}</strong></div><div class="sync-row"><i class="bx bx-signal-5"></i><span>Status da conexao</span><strong>${data.last_cloud_ok_at?'Online':(data.cloud_configured?'Aguardando':'Pendente')}</strong></div>`;}
    function processingRows(data){const total=Number(data.cameras_total||0);const online=Number(data.cameras_online||0);const cpu=data.cpu_percent==null?'n/d':`${Math.round(data.cpu_percent)}%`;const ram=data.ram_percent==null?'n/d':`${Math.round(data.ram_percent)}%`;return `<div class="list-item"><div><strong>Cameras processadas</strong><small>${online}/${total} online</small></div><span>${total?Math.round((online/total)*100):0}%</span></div><div class="list-item"><div><strong>FPS</strong><small>Calculado por camera quando Vision estiver ativo.</small></div><span>dinamico</span></div><div class="list-item"><div><strong>CPU</strong><small>Uso local monitorado pelo Windows.</small></div><span>${cpu}</span></div><div class="list-item"><div><strong>RAM</strong><small>Cache de frames e fila local.</small></div><span>${ram}</span></div><div class="list-item"><div><strong>Eventos processados</strong><small>Fila local antes da Cloud.</small></div><span>${data.queue_size||0}</span></div>`;}
    function diagnosticsRows(data){return `<div class="list-item"><div><strong>Sistema</strong><small>Windows local / servico CAMPEX Node.</small></div><span>OK</span></div><div class="list-item"><div><strong>Banco local</strong><small>SQLite em pasta do usuario.</small></div><span>OK</span></div><div class="list-item"><div><strong>Rede</strong><small>Conexao de saida com a CAMPEX Cloud.</small></div><span>${data.cloud_configured?'Configurada':'Pendente'}</span></div><div class="list-item"><div><strong>Cameras</strong><small>${data.cameras_online||0}/${data.cameras_total||0} online</small></div><span>${data.cameras_total||0}</span></div><div class="list-item"><div><strong>Fila</strong><small>Eventos aguardando sincronizacao.</small></div><span>${data.queue_size||0}</span></div><div class="list-item"><div><strong>Versao</strong><small>CAMPEX Node local</small></div><span>0.1.0</span></div>`;}
    async function load(){const data=await fetch('/api/status').then(r=>r.json());const total=Number(data.cameras_total||0);const online=Number(data.cameras_online||0);const queue=Number(data.queue_size||0);document.querySelector('#cloud-badge').textContent=data.paired?'Conectado a CAMPEX Cloud':(data.cloud_configured?'Cloud configurada':'Cloud nao configurada');document.querySelector('#sync-caption').textContent='Ultima sincronizacao: '+formatTime(data.last_sync_at);document.querySelector('#total').textContent=total;document.querySelector('#online').textContent=online;document.querySelector('#queue').textContent=queue;document.querySelector('#camera-bar').style.width=total?`${Math.round((online/total)*100)}%`:'0%';document.querySelector('#node-id').textContent=data.node_id||'-';document.querySelector('#cloud-url-label').textContent=data.cloud_url||'-';document.querySelector('#uptime-label').textContent=uptimeText(data.uptime_seconds);document.querySelector('#resources-label').textContent=`CPU ${data.cpu_percent==null?'n/d':Math.round(data.cpu_percent)+'%'} / RAM ${data.ram_percent==null?'n/d':Math.round(data.ram_percent)+'%'}`;document.querySelector('#data-dir-label').textContent=data.data_dir||'OK';document.querySelector('#logs-dir-label').textContent=data.logs_dir||'OK';document.querySelector('[name=cloud_url]').value=data.cloud_url||'';const cameras=data.cameras||[];const cameraHtml=cameras.map(cameraCard).join('')||'<p class="status">Nenhuma camera sincronizada ainda.</p>';document.querySelector('#cameras').innerHTML=cameraHtml;document.querySelector('#cameras-page').innerHTML=cameraHtml;document.querySelector('#events-list').innerHTML=eventRows(cameras);document.querySelector('#events-page').innerHTML=eventRows(cameras);document.querySelector('#sync-summary').innerHTML=syncRows(data);document.querySelector('#sync-page').innerHTML=syncRows(data);document.querySelector('#processing-page').innerHTML=processingRows(data);document.querySelector('#diagnostics-page').innerHTML=diagnosticsRows(data);document.querySelector('#diag-cloud').textContent=data.paired?'Pareado':(data.cloud_configured?'Configurado':'Pendente');}
    document.querySelectorAll('.nav button,[data-page-jump]').forEach(btn=>btn.addEventListener('click',()=>setPage(btn.dataset.page||btn.dataset.pageJump)));
    document.querySelector('#connect-form').addEventListener('submit',async e=>{e.preventDefault();statusEl().textContent='Conectando...';const form=e.currentTarget;const body={cloud_url:form.cloud_url.value,pairing_code:form.pairing_code.value,node_name:form.node_name.value};const res=await fetch('/api/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();statusEl().textContent=data.ok?(data.message||'Pareado. O Node buscara configuracoes e enviara eventos para a Cloud.'):(data.error||'Falha ao parear.');await load();});
    async function syncNow(){const el=statusEl();if(el)el.textContent='Sincronizando...';const res=await fetch('/api/sync',{method:'POST'});const data=await res.json();if(el)el.textContent=data.ok?`Sincronizadas: ${data.cameras_loaded}`:(data.error||'Falha na sincronizacao');await load();}
    let pairingTimer=null;async function startPairing(){const form=document.querySelector('#connect-form');const el=statusEl();if(el)el.textContent='Gerando codigo...';const res=await fetch('/api/pairing/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cloud_url:form.cloud_url.value,node_name:form.node_name.value||'CAMPEX Node'})});const data=await res.json();if(!data.ok){if(el)el.textContent=data.error||'Falha ao gerar codigo.';return;}const box=document.querySelector('#local-pairing-code');box.style.display='block';box.innerHTML=`<h2 style="font-size:28px;letter-spacing:.16em;margin:.25rem 0">${data.pairing_code}</h2><p>Acesse CAMPEX Web > Configuracoes > Nodes > Conectar Node e digite este codigo. Expira em ${data.expires_at}.</p>`;if(el)el.textContent='Aguardando autorizacao no painel...';clearInterval(pairingTimer);pairingTimer=setInterval(checkPairingStatus,3000);}
    async function checkPairingStatus(){const el=statusEl();const res=await fetch('/api/pairing/status');const data=await res.json();if(data.status==='authorized'){clearInterval(pairingTimer);if(el)el.textContent='Node conectado a CAMPEX Cloud.';document.querySelector('#local-pairing-code').style.display='none';await load();}else if(data.status==='expired'){clearInterval(pairingTimer);if(el)el.textContent='Codigo expirado. Gere um novo codigo.';}}
    async function testCamera(){const form=document.querySelector('#camera-form');const el=document.querySelector('#camera-form-status');el.textContent='Testando RTSP...';const res=await fetch('/api/cameras/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rtsp_url:form.rtsp_url.value})});const data=await res.json();el.textContent=data.ok?`Conexao OK - ${data.resolution.width||'?'}x${data.resolution.height||'?'}`:(data.error||'Nao foi possivel abrir o stream.');}
    async function saveCamera(event){event.preventDefault();const form=document.querySelector('#camera-form');const el=document.querySelector('#camera-form-status');el.textContent='Salvando camera...';const res=await fetch('/api/cameras',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.camera_name.value,rtsp_url:form.rtsp_url.value,enabled:form.enabled.checked})});const data=await res.json();el.textContent=data.ok?'Camera salva. Worker local iniciado quando ativado.':(data.error||'Falha ao salvar camera.');if(data.ok){form.camera_name.value='';form.rtsp_url.value='';}await load();}
    document.querySelector('#sync-button').addEventListener('click',syncNow);document.querySelector('#sync-button-cameras').addEventListener('click',syncNow);document.querySelector('#diagnostics-button').addEventListener('click',async()=>{const data=await fetch('/api/diagnostics').then(r=>r.json());const el=statusEl();if(el)el.textContent=`Diagnostico OK - fila ${data.queue_size} - cameras ${data.cameras.cameras_total}`;});document.querySelector('#diagnostics-button-page').addEventListener('click',load);
    document.querySelector('#start-pairing-button').addEventListener('click',startPairing);
    document.querySelector('#test-camera-button').addEventListener('click',testCamera);
    document.querySelector('#camera-form').addEventListener('submit',saveCamera);
    load();setInterval(load,5000);
  </script>
</body>
</html>"""
